name: face-id-app

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ADAFACE_CKPT_URL: "https://huggingface.co/VishalMishraTss/AdaFace/resolve/main/adaface_ir50_ms1mv2.ckpt"
        ADAFACE_CKPT_NAME: "adaface_ir50_ms1mv2.ckpt"
        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_models:/models
    working_dir: /app
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      INSIGHTFACE_HOME: "/app/models/insightface/"
      ADAFACE_CKPT_PATH: "/models/adaface/pretrained/adaface_ir50_ms1mv2.ckpt"
    command: >
      bash -lc "
      python -m pip install --no-cache-dir -e . &&
      uvicorn server:app --host 0.0.0.0 --port 8000
      "

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    depends_on:
      - backend

volumes:
  backend_models:
